### ISSUE TITLE
Issue from AskUbuntu Question https://askubuntu.com/q/1378822/739431

### ISSUE THREAD

**Issue by PRATAP-KUMAR** [Zany-Zachary1/Mock-Universal-Menu#1]
[MUM.zip](https://github.com/Zany-Zachary1/Mock-Universal-Menu/files/7662834/MUM.zip)

Hi, Can you try this extension?

**Comment by Zany-Zachary1** [comment]
Oh dear lord, I'm just mildly stupid.  I'm so sorry for wasting your time.  After comparing the code, I had forgotten to delete the original line in my extension.js.  So sorry again, but yours worked.  Feel free to post the answer on AskUbuntu.
